# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitledRbejpv.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QMainWindow,
    QPushButton, QRadioButton, QSizePolicy, QStatusBar,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(736, 320)
        MainWindow.setAcceptDrops(True)
        MainWindow.setAnimated(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(90, 10, 50, 31))
        self.label.setTextFormat(Qt.TextFormat.MarkdownText)
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 50, 50, 20))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cb_sss = QComboBox(self.centralwidget)
        self.cb_sss.setObjectName(u"cb_sss")
        self.cb_sss.setGeometry(QRect(80, 51, 67, 21))
        self.pb_sss = QPushButton(self.centralwidget)
        self.pb_sss.setObjectName(u"pb_sss")
        self.pb_sss.setGeometry(QRect(170, 50, 61, 24))
        self.rb_sss_0 = QRadioButton(self.centralwidget)
        self.rb_sss_0.setObjectName(u"rb_sss_0")
        self.rb_sss_0.setGeometry(QRect(20, 100, 51, 20))
        self.rb_sss_1 = QRadioButton(self.centralwidget)
        self.rb_sss_1.setObjectName(u"rb_sss_1")
        self.rb_sss_1.setGeometry(QRect(20, 130, 51, 20))
        self.rb_sss_2 = QRadioButton(self.centralwidget)
        self.rb_sss_2.setObjectName(u"rb_sss_2")
        self.rb_sss_2.setGeometry(QRect(20, 160, 51, 20))
        self.rb_sss_3 = QRadioButton(self.centralwidget)
        self.rb_sss_3.setObjectName(u"rb_sss_3")
        self.rb_sss_3.setGeometry(QRect(20, 190, 51, 20))
        self.rb_sss_4 = QRadioButton(self.centralwidget)
        self.rb_sss_4.setObjectName(u"rb_sss_4")
        self.rb_sss_4.setGeometry(QRect(20, 220, 51, 20))
        self.te_sss_distance = QTextEdit(self.centralwidget)
        self.te_sss_distance.setObjectName(u"te_sss_distance")
        self.te_sss_distance.setEnabled(True)
        self.te_sss_distance.setGeometry(QRect(170, 140, 61, 21))
        self.te_sss_distance.setAcceptDrops(False)
        self.te_sss_distance.setTabChangesFocus(True)
        self.te_sss_distance.setTextInteractionFlags(Qt.TextInteractionFlag.TextEditorInteraction)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(110, 140, 50, 16))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pb_sss_start = QPushButton(self.centralwidget)
        self.pb_sss_start.setObjectName(u"pb_sss_start")
        self.pb_sss_start.setGeometry(QRect(40, 270, 75, 24))
        self.pb_sss_stop = QPushButton(self.centralwidget)
        self.pb_sss_stop.setObjectName(u"pb_sss_stop")
        self.pb_sss_stop.setGeometry(QRect(130, 270, 75, 24))
        self.cb_rpm_sss = QComboBox(self.centralwidget)
        self.cb_rpm_sss.setObjectName(u"cb_rpm_sss")
        self.cb_rpm_sss.setGeometry(QRect(166, 100, 61, 22))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 100, 50, 16))
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(100, 190, 50, 16))
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.te_sss_sate = QTextEdit(self.centralwidget)
        self.te_sss_sate.setObjectName(u"te_sss_sate")
        self.te_sss_sate.setEnabled(True)
        self.te_sss_sate.setGeometry(QRect(170, 190, 61, 41))
        self.te_sss_sate.setAcceptDrops(False)
        self.te_sss_sate.setTabChangesFocus(True)
        self.te_sss_sate.setTextInteractionFlags(Qt.TextInteractionFlag.TextEditorInteraction)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(340, 10, 50, 31))
        self.label_6.setTextFormat(Qt.TextFormat.MarkdownText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cb_rpm_mag = QComboBox(self.centralwidget)
        self.cb_rpm_mag.setObjectName(u"cb_rpm_mag")
        self.cb_rpm_mag.setGeometry(QRect(416, 100, 61, 22))
        self.rb_mag_0 = QRadioButton(self.centralwidget)
        self.rb_mag_0.setObjectName(u"rb_mag_0")
        self.rb_mag_0.setGeometry(QRect(270, 100, 51, 20))
        self.rb_mag_4 = QRadioButton(self.centralwidget)
        self.rb_mag_4.setObjectName(u"rb_mag_4")
        self.rb_mag_4.setGeometry(QRect(270, 220, 51, 20))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(270, 50, 50, 20))
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(360, 140, 50, 16))
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pb_mag_start = QPushButton(self.centralwidget)
        self.pb_mag_start.setObjectName(u"pb_mag_start")
        self.pb_mag_start.setGeometry(QRect(290, 270, 75, 24))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(350, 190, 50, 16))
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.te_mag_state = QTextEdit(self.centralwidget)
        self.te_mag_state.setObjectName(u"te_mag_state")
        self.te_mag_state.setEnabled(True)
        self.te_mag_state.setGeometry(QRect(420, 190, 61, 41))
        self.te_mag_state.setAcceptDrops(False)
        self.te_mag_state.setTabChangesFocus(True)
        self.te_mag_state.setTextInteractionFlags(Qt.TextInteractionFlag.TextEditorInteraction)
        self.rb_mag_1 = QRadioButton(self.centralwidget)
        self.rb_mag_1.setObjectName(u"rb_mag_1")
        self.rb_mag_1.setGeometry(QRect(270, 130, 51, 20))
        self.pb_mag = QPushButton(self.centralwidget)
        self.pb_mag.setObjectName(u"pb_mag")
        self.pb_mag.setGeometry(QRect(420, 50, 61, 24))
        self.cb_mag = QComboBox(self.centralwidget)
        self.cb_mag.setObjectName(u"cb_mag")
        self.cb_mag.setGeometry(QRect(330, 51, 67, 21))
        self.te_mag_distance = QTextEdit(self.centralwidget)
        self.te_mag_distance.setObjectName(u"te_mag_distance")
        self.te_mag_distance.setEnabled(True)
        self.te_mag_distance.setGeometry(QRect(420, 140, 61, 21))
        self.te_mag_distance.setAcceptDrops(False)
        self.te_mag_distance.setTabChangesFocus(True)
        self.te_mag_distance.setTextInteractionFlags(Qt.TextInteractionFlag.TextEditorInteraction)
        self.rb_mag_3 = QRadioButton(self.centralwidget)
        self.rb_mag_3.setObjectName(u"rb_mag_3")
        self.rb_mag_3.setGeometry(QRect(270, 190, 51, 20))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(350, 100, 50, 16))
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.rb_mag_2 = QRadioButton(self.centralwidget)
        self.rb_mag_2.setObjectName(u"rb_mag_2")
        self.rb_mag_2.setGeometry(QRect(270, 160, 51, 20))
        self.pb_mag_stop = QPushButton(self.centralwidget)
        self.pb_mag_stop.setObjectName(u"pb_mag_stop")
        self.pb_mag_stop.setGeometry(QRect(380, 270, 75, 24))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(580, 10, 50, 31))
        self.label_11.setTextFormat(Qt.TextFormat.MarkdownText)
        self.label_11.setScaledContents(False)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cb_rpm_ss = QComboBox(self.centralwidget)
        self.cb_rpm_ss.setObjectName(u"cb_rpm_ss")
        self.cb_rpm_ss.setGeometry(QRect(656, 100, 61, 22))
        self.rb_ss_0 = QRadioButton(self.centralwidget)
        self.rb_ss_0.setObjectName(u"rb_ss_0")
        self.rb_ss_0.setGeometry(QRect(510, 100, 51, 20))
        self.rb_ss_4 = QRadioButton(self.centralwidget)
        self.rb_ss_4.setObjectName(u"rb_ss_4")
        self.rb_ss_4.setGeometry(QRect(510, 220, 51, 20))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(510, 50, 50, 20))
        self.label_12.setScaledContents(False)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(600, 140, 50, 16))
        self.label_13.setScaledContents(False)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pb_ss_start = QPushButton(self.centralwidget)
        self.pb_ss_start.setObjectName(u"pb_ss_start")
        self.pb_ss_start.setGeometry(QRect(530, 270, 75, 24))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(590, 190, 50, 16))
        self.label_14.setScaledContents(False)
        self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.te_ss_state = QTextEdit(self.centralwidget)
        self.te_ss_state.setObjectName(u"te_ss_state")
        self.te_ss_state.setEnabled(True)
        self.te_ss_state.setGeometry(QRect(660, 190, 61, 41))
        self.te_ss_state.setAcceptDrops(False)
        self.te_ss_state.setTabChangesFocus(True)
        self.te_ss_state.setTextInteractionFlags(Qt.TextInteractionFlag.TextEditorInteraction)
        self.rb_ss_1 = QRadioButton(self.centralwidget)
        self.rb_ss_1.setObjectName(u"rb_ss_1")
        self.rb_ss_1.setGeometry(QRect(510, 130, 51, 20))
        self.pb_ss = QPushButton(self.centralwidget)
        self.pb_ss.setObjectName(u"pb_ss")
        self.pb_ss.setGeometry(QRect(660, 50, 61, 24))
        self.cb_ss = QComboBox(self.centralwidget)
        self.cb_ss.setObjectName(u"cb_ss")
        self.cb_ss.setGeometry(QRect(570, 51, 67, 21))
        self.te_ss_distance = QTextEdit(self.centralwidget)
        self.te_ss_distance.setObjectName(u"te_ss_distance")
        self.te_ss_distance.setEnabled(True)
        self.te_ss_distance.setGeometry(QRect(660, 140, 61, 21))
        self.te_ss_distance.setAcceptDrops(False)
        self.te_ss_distance.setTabChangesFocus(True)
        self.te_ss_distance.setTextInteractionFlags(Qt.TextInteractionFlag.TextEditorInteraction)
        self.rb_ss_3 = QRadioButton(self.centralwidget)
        self.rb_ss_3.setObjectName(u"rb_ss_3")
        self.rb_ss_3.setGeometry(QRect(510, 190, 51, 20))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(590, 100, 50, 16))
        self.label_15.setScaledContents(False)
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.rb_ss_2 = QRadioButton(self.centralwidget)
        self.rb_ss_2.setObjectName(u"rb_ss_2")
        self.rb_ss_2.setGeometry(QRect(510, 160, 51, 20))
        self.pb_ss_stop = QPushButton(self.centralwidget)
        self.pb_ss_stop.setObjectName(u"pb_ss_stop")
        self.pb_ss_stop.setGeometry(QRect(620, 270, 75, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\ubaa8\ud130 \ucee8\ud2b8\ub864 \ud504\ub85c\uadf8\ub7a8", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"## SSS", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.pb_sss.setText(QCoreApplication.translate("MainWindow", u"\uc5f4\uae30", None))
        self.rb_sss_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.rb_sss_1.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.rb_sss_2.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.rb_sss_3.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.rb_sss_4.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\uc774\ub3d9\uac70\ub9ac", None))
        self.pb_sss_start.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc791", None))
        self.pb_sss_stop.setText(QCoreApplication.translate("MainWindow", u"\uc815\uc9c0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\uc0c1\ud0dc", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"## Mag", None))
        self.rb_mag_0.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.rb_mag_4.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\uc774\ub3d9\uac70\ub9ac", None))
        self.pb_mag_start.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc791", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\uc0c1\ud0dc", None))
        self.rb_mag_1.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.pb_mag.setText(QCoreApplication.translate("MainWindow", u"\uc5f4\uae30", None))
        self.rb_mag_3.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.rb_mag_2.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pb_mag_stop.setText(QCoreApplication.translate("MainWindow", u"\uc815\uc9c0", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"## SS", None))
        self.rb_ss_0.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.rb_ss_4.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\uc774\ub3d9\uac70\ub9ac", None))
        self.pb_ss_start.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc791", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\uc0c1\ud0dc", None))
        self.rb_ss_1.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.pb_ss.setText(QCoreApplication.translate("MainWindow", u"\uc5f4\uae30", None))
        self.rb_ss_3.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.rb_ss_2.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pb_ss_stop.setText(QCoreApplication.translate("MainWindow", u"\uc815\uc9c0", None))
    # retranslateUi

